spring:
  kafka:
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: '1'
      properties:
        linger:
          ms: '0'
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: '0'
      batch-size: '16384'
      buffer-memory: '33554432'
    consumer:
      auto:
        commit:
          interval:
            ms: '1000'
      enable-auto-commit: 'true'
      auto-offset-reset: latest
      properties:
        group:
          id: defaultConsumerGroup
        request:
          timeout:
            ms: '180000'
        session:
          timeout:
            ms: '120000'
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    bootstrap-servers: 127.0.0.1:9092
    listener:
      missing-topics-fatal: 'false'

