spring:
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: hello_kafka
  redis:
    host: localhost
    pool: 6379
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
server:
  port: 80

