server:
  port: 8090
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate


  datasource:
    url: jdbc:mysql://localhost:3306/quickbuy?serverTimezone=GMT
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
